"""
OutputManager - Manages FDS input file generation.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from ...utils import get_logger
from .base import BaseManager

if TYPE_CHECKING:
    from ..namelists import Head, Time
    from .control import ControlManager
    from .geometry import GeometryManager
    from .instrumentation import InstrumentationManager
    from .material import MaterialManager
    from .physics import PhysicsManager
    from .ramp import RampManager
    from .species import SpeciesManager

logger = get_logger(__name__)


class OutputManager(BaseManager):
    """
    Manages FDS input file generation.

    This manager handles converting simulation components into
    FDS-formatted text and writing output files.
    """

    def __init__(
        self,
        geometry: GeometryManager,
        material_mgr: MaterialManager,
        physics: PhysicsManager,
        species_mgr: SpeciesManager,
        instrumentation: InstrumentationManager,
        controls: ControlManager,
        ramps: RampManager,
        head: Head,
        time_params: Time | None,
    ):
        """Initialize the output manager with references to all managers."""
        super().__init__()
        self.geometry = geometry
        self.material_mgr = material_mgr
        self.physics = physics
        self.species_mgr = species_mgr
        self.instrumentation = instrumentation
        self.controls = controls
        self.ramps = ramps
        self._head = head
        self._time_params = time_params

    def to_fds(self) -> str:
        """
        Generate the complete FDS input file content.

        Returns
        -------
        str
            FDS input file content
        """
        lines = []

        # Add header comment
        lines.append("! FDS input file generated by PyFDS")
        if self._head.title:
            lines.append(f"! {self._head.title}")
        lines.append("")

        # HEAD namelist
        lines.append(self._head.to_fds())

        # TIME namelist
        if self._time_params:
            lines.append(self._time_params.to_fds())

        # MISC namelist (should appear near top)
        if self.physics.misc_params:
            lines.append("! --- Miscellaneous Parameters ---")
            lines.append(self.physics.misc_params.to_fds())

        # MESH namelists
        if self.geometry.meshes:
            lines.append("! --- Meshes ---")
            for mesh in self.geometry.meshes:
                lines.append(mesh.to_fds())

        # RAMP namelists (must come before MATL that reference them)
        if self.ramps.ramps:
            lines.append("! --- Ramps ---")
            for ramp in self.ramps.ramps:
                lines.append(ramp.to_fds())

        # SPEC namelists (after RAMP, before REAC)
        if self.species_mgr.species:
            lines.append("! --- Species ---")
            for spec in self.species_mgr.species:
                lines.append(spec.to_fds())

        # REAC namelist
        if self.physics.reactions:
            lines.append("! --- Reactions ---")
            for reaction in self.physics.reactions:
                lines.append(reaction.to_fds())

        # COMB namelist (after REAC)
        if self.species_mgr.combustion:
            lines.append("! --- Combustion Parameters ---")
            lines.append(self.species_mgr.combustion.to_fds())

        # MATL namelists
        if self.material_mgr.materials:
            lines.append("! --- Materials ---")
            for material in self.material_mgr.materials:
                lines.append(material.to_fds())

        # SURF namelists
        if self.material_mgr.surfaces:
            lines.append("! --- Surfaces ---")
            for surface in self.material_mgr.surfaces:
                lines.append(surface.to_fds())

        # PROP namelists
        if self.instrumentation.props:
            lines.append("! --- Device Properties ---")
            for prop in self.instrumentation.props:
                lines.append(prop.to_fds())

        # MULT namelists (must come before objects that reference them)
        if self.geometry.multipliers:
            lines.append("! --- Multipliers ---")
            for mult in self.geometry.multipliers:
                lines.append(mult.to_fds())

        # OBST namelists
        if self.geometry.obstructions:
            lines.append("! --- Obstructions ---")
            for obst in self.geometry.obstructions:
                lines.append(obst.to_fds())

        # HOLE namelists (must come after OBST)
        if self.geometry.holes:
            lines.append("! --- Holes ---")
            for hole in self.geometry.holes:
                lines.append(hole.to_fds())

        # VENT namelists (after OBST and SURF)
        if self.geometry.vents:
            lines.append("! --- Vents ---")
            for vent in self.geometry.vents:
                lines.append(vent.to_fds())

        # CTRL namelists
        if self.controls.ctrls:
            lines.append("! --- Controls ---")
            for ctrl in self.controls.ctrls:
                lines.append(ctrl.to_fds())

        # DEVC namelists
        if self.instrumentation.devices:
            lines.append("! --- Devices ---")
            for device in self.instrumentation.devices:
                lines.append(device.to_fds())

        # INIT namelists
        if self.controls.inits:
            lines.append("! --- Initial Conditions ---")
            for init in self.controls.inits:
                lines.append(init.to_fds())

        # TAIL namelist
        lines.append("\n&TAIL /")

        return "\n".join(lines)

    def write(self, filename: str | Path, content: str) -> Path:
        """
        Write the FDS input file to disk.

        Parameters
        ----------
        filename : str or Path
            Path to output file (should have .fds extension)
        content : str
            FDS input file content to write

        Returns
        -------
        Path
            Path to the written file
        """
        filepath = Path(filename)

        # Ensure .fds extension
        if filepath.suffix != ".fds":
            filepath = filepath.with_suffix(".fds")

        # Create parent directories if needed
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        filepath.write_text(content)

        logger.info(f"Wrote FDS input file: {filepath}")
        return filepath
