#!/usr/bin/env python3
"""
Mesh Output Configuration Example
=================================

Demonstrates mesh-level output options including boundary file
output control and mesh-specific settings.

FDS Reference: Heat_Transfer/heat_conduction_a.fds
https://github.com/firemodels/fds/blob/master/Verification/Heat_Transfer/heat_conduction_a.fds

Key Namelists: MESH (BNDF_MESH), MISC (BNDF_DEFAULT), OBST (BNDF_OBST)

Usage
-----
    python mesh_output.py

Output
------
    fds/output/mesh_output.fds
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from examples._common import write_example
from pyfds import Simulation
from pyfds.core.geometry import Bounds3D, Grid3D, Point3D
from pyfds.core.namelists import (
    Device,
    Material,
    Mesh,
    Misc,
    Obstruction,
    Reaction,
    Surface,
    Time,
    Vent,
)


def main():
    """Create a simulation demonstrating mesh-level output control."""

    # Create simulation
    sim = Simulation(
        chid="mesh_output",
        title="Mesh Output Configuration Example",
    )

    # Time parameters
    sim.add(Time(t_end=60.0))

    # ==========================================================================
    # MISC output settings
    # ==========================================================================

    # BNDF_DEFAULT controls whether boundary files are generated by default
    # Setting to False reduces output file size significantly
    sim.add(
        Misc(
            bndf_default=True,  # Enable boundary file output (default)
            overwrite=True,  # Overwrite existing files
        )
    )

    # ==========================================================================
    # Meshes with output control
    # ==========================================================================

    # Mesh 1: Standard mesh with boundary output enabled
    sim.add(
        Mesh(
            id="MESH1",
            ijk=Grid3D.of(20, 20, 20),
            xb=Bounds3D.of(0.0, 2.0, 0.0, 2.0, 0.0, 2.0),
            bndf_mesh=True,  # Generate BNDF for this mesh
        )
    )

    # Mesh 2: Extended mesh with boundary output disabled
    # (useful for background/extension meshes)
    sim.add(
        Mesh(
            id="MESH2",
            ijk=Grid3D.of(20, 20, 10),
            xb=Bounds3D.of(0.0, 2.0, 0.0, 2.0, 2.0, 3.0),
            bndf_mesh=False,  # No BNDF for this mesh (save space)
        )
    )

    # ==========================================================================
    # Materials and surfaces for boundary output demo
    # ==========================================================================

    # Concrete material for walls
    sim.add(
        Material(
            id="CONCRETE",
            conductivity=1.6,
            specific_heat=0.9,
            density=2300.0,
            emissivity=0.9,
        )
    )

    # Wall surface
    sim.add(
        Surface(
            id="CONCRETE_WALL",
            matl_id="CONCRETE",
            thickness=0.2,
            color="GRAY 60",
        )
    )

    # Fire surface
    sim.add(Reaction(fuel="PROPANE", soot_yield=0.01))
    sim.add(Surface(id="FIRE", hrrpua=500.0, color="ORANGE"))

    # ==========================================================================
    # Obstructions with BNDF control
    # ==========================================================================

    # Wall with boundary output enabled (surface temperatures recorded)
    sim.add(
        Obstruction(
            id="BACK_WALL",
            xb=Bounds3D.of(0.0, 0.1, 0.0, 2.0, 0.0, 2.0),
            surf_id="CONCRETE_WALL",
            bndf_obst=True,  # Include in boundary file output
        )
    )

    # Side wall with boundary output disabled (not of interest)
    sim.add(
        Obstruction(
            id="SIDE_WALL",
            xb=Bounds3D.of(0.0, 2.0, 1.9, 2.0, 0.0, 2.0),
            surf_id="CONCRETE_WALL",
            bndf_obst=False,  # Exclude from boundary output
        )
    )

    # Target obstruction for heat flux measurement
    sim.add(
        Obstruction(
            id="TARGET",
            xb=Bounds3D.of(1.5, 1.6, 0.5, 0.6, 0.0, 1.0),
            surf_id="CONCRETE_WALL",
            bndf_obst=True,
        )
    )

    # Fire vent
    sim.add(
        Vent(
            xb=Bounds3D.of(0.8, 1.2, 0.8, 1.2, 0.0, 0.0),
            surf_id="FIRE",
        )
    )

    # Open top
    sim.add(Vent(mb="ZMAX", surf_id="OPEN"))

    # ==========================================================================
    # Monitoring devices
    # ==========================================================================

    # Wall surface temperature
    sim.add(
        Device(
            id="WALL_TEMP",
            xyz=Point3D(0.1, 1.0, 1.0),
            quantity="WALL TEMPERATURE",
            ior=-1,  # -X face of wall
        )
    )

    # Wall heat flux
    sim.add(
        Device(
            id="WALL_HF",
            xyz=Point3D(0.1, 1.0, 1.0),
            quantity="NET HEAT FLUX",
            ior=-1,
        )
    )

    # Target surface temperature
    sim.add(
        Device(
            id="TARGET_TEMP",
            xyz=Point3D(1.5, 0.55, 0.5),
            quantity="WALL TEMPERATURE",
            ior=2,  # +Y face
        )
    )

    # Gas temperature near wall
    sim.add(
        Device(
            id="GAS_TEMP_WALL",
            xyz=Point3D(0.2, 1.0, 1.0),
            quantity="TEMPERATURE",
        )
    )

    # HRR
    sim.add(
        Device(
            id="HRR",
            xb=Bounds3D.of(0.0, 2.0, 0.0, 2.0, 0.0, 3.0),
            quantity="HRR",
        )
    )

    # Write output
    output_path = write_example(sim, "output")
    print(f"Created: {output_path}")

    print("\nGenerated FDS file:")
    print("-" * 40)
    print(sim.to_fds())


if __name__ == "__main__":
    main()
